version: "3.7"

# These services depends on configuration from files:
#  - docker-compose.yml

services:

  spark-master:
    container_name: spark-master
    image: bde2020/spark-master:2.4.5-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
    ports:
      - 28000:8080
      - 28007:7077
    expose:
      - 7337
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  spark-worker-1:
    container_name: spark-worker-1
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
      - ./docker/spark-worker/worker.sh:/worker.sh
    depends_on:
      - spark-master
    ports:
      - 28011:8081
    expose:
      - 7337
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  spark-worker-2:
    container_name: spark-worker-2
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
      - ./docker/spark-worker/worker.sh:/worker.sh
    depends_on:
      - spark-master
    ports:
      - 28021:8081
    expose:
      - 7337
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  jupyter:
    depends_on:
      - spark-master
      - keycloak
