version: "3.7"
services:
  spark-master:
    container_name: spark-master
    image: bde2020/spark-master:2.4.4-hadoop2.7
    volumes:
      - ./data:/data
      - ../dapla-spark-plugin/secret:/secret
    ports:
      - 28000:8080
      - 28007:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  spark-worker-1:
    container_name: spark-worker-1
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    volumes:
      - ./data:/data
      - ../dapla-spark-plugin/secret:/secret
    depends_on:
      - spark-master
    ports:
      - 28011:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  spark-worker-2:
    container_name: spark-worker-2
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    volumes:
      - ./data:/data
      - ../dapla-spark-plugin/secret:/secret
    depends_on:
      - spark-master
    ports:
      - 28021:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  hadoop:
    container_name: hadoop
    image: sequenceiq/hadoop-docker:2.7.1
    ports:
      - 50070:50070
      - 50010:50010
      - 9000:9000

  zeppelin:
    container_name: zeppelin-notebook
    image: lds-zeppelin:latest
    volumes:
      - ./data:/data
      - ../dapla-spark-plugin/secret:/secret
      - ./notebook:/notebook:delegated
    build:
      context: ../
      dockerfile: ${PWD}/docker/zeppelin/Dockerfile
    depends_on:
      - spark-master
    ports:
      - 28010:8080
    env_file:
      - .env
    environment:
      - SPARK_MASTER_HOST=spark://spark-master
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - SPARK_LOCAL_IP=zeppelin
      - SPARK_PRINT_LAUNCH_COMMAND=true
      - ZEPPELIN_ADDR=0.0.0.0
      - DAPLA_SPARK_GCS_STORAGE=file:///data/datastore
      - DAPLA_SPARK_DATA_ACCESS_URL=http://data-access-service:10140

  pubsub:
    container_name: pubsub
    image: pubsub-emulator:latest
    build:
      context: docker/pubsub-emulator
      dockerfile: Dockerfile
    ports:
      - 8538:8538

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.16
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  db-admin:
    container_name: db-admin
    image: adminer
    ports:
      - 25430:8080

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    ports:
      - 25432:5432
    volumes:
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  dapla-catalog-service:
    container_name: dapla-catalog-service
    build:
      context: ../dapla-catalog
      dockerfile: Dockerfile
    image: dapla-catalog-service:dev
    ports:
      - 20110:10110
      - 20118:10118
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/catalog
      AUTH_dash_SERVICE_HOST: dapla-auth-dataset-service
      AUTH_dash_SERVICE_PORT: 10108
      PUBSUB_EMULATOR_HOST: pubsub
      PUBSUB_EMULATOR_PORT: 8538
      TRACING_HOST: jaeger
    depends_on:
      - postgres
      - jaeger
      - pubsub
      - dapla-auth-dataset-service

  dapla-auth-dataset-service:
    container_name: dapla-auth-dataset-service
    build:
      context: ../dataset-access
      dockerfile: Dockerfile
    image: dapla-auth-dataset-service:dev
    ports:
      - 20100:10100
      - 20108:10108
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/dataset_access
      TRACING_HOST: jaeger
    depends_on:
      - postgres
      - jaeger

  data-access-service:
    container_name: data-access-service
    build:
      context: ../data-access
      dockerfile: Dockerfile
    image: data-access-service:dev
    ports:
      - 20140:10140
      - 20148:10148
    volumes:
      - ../dapla-spark-plugin/secret:/secret
    environment:
      TRACING_HOST: jaeger
      DATA_ACCESS_SERVICE_ACCOUNT_KEY_FILE: /secret/gcs_sa_test.json
      DATA_ACCESS_SERVICE_DEFAULT_LOCATION: gs://dev-datalager-store
    depends_on:
      - jaeger
      - dapla-auth-dataset-service
      - dapla-catalog-service

  metadata-distributor:
    container_name: metadata-distributor
    build:
      context: ../metadata-distributor
      dockerfile: Dockerfile
    image: metadata-distributor:dev
    ports:
      - 20160:10160
      - 20168:10168
    environment:
      PUBSUB_EMULATOR_HOST: pubsub
      PUBSUB_EMULATOR_PORT: 8538
      TRACING_HOST: jaeger
    depends_on:
      - jaeger
      - pubsub

