version: "3.7"

services:

  jupyter:
    container_name: jupyter
    image: eu.gcr.io/prod-bip/dapla-jupyter
    volumes:
      - ./data:/data:delegated
      - ./docker/jupyter/jupyterhub_config.py:/jupyter/jupyterhub_config.py
      - ./docker/jupyter/spark-localstack.conf:/usr/lib/spark/conf/spark-defaults.conf
    build:
      context: ../dapla-spark-plugin
      dockerfile: ${PWD}/../dapla-spark-plugin/docker/jupyter/Dockerfile
    depends_on:
      - keycloak
    ports:
      - 28012:8000
    environment:
      - JUPYTERHUB_HANDLER_CUSTOM_AUTH_URL=https://127.0.0.1:8081/hub/custom-api/user
      - SPARK_USER_TOKEN_EXPIRY_BUFFER_SECS=120
      - OAUTH2_AUTH_URL=http://localhost:28081/auth/realms/ssb/protocol/openid-connect/auth
      - OAUTH2_TOKEN_URL=http://keycloak:8080/auth/realms/ssb/protocol/openid-connect/token
      - OAUTH2_USERDATA_URL=http://keycloak:8080/auth/realms/ssb/protocol/openid-connect/userinfo
      - OAUTH2_CALLBACK_URL=http://localhost:28012/hub/oauth_callback
      - OAUTH_CLIENT_ID=jupyter
      - OAUTH_CLIENT_SECRET=f506d183-77ec-446c-a51b-af4ec7daef81
      - METADATA_PUBLISHER_URL=http://metadata-distributor:10160
      - DATA_ACCESS_URL=http://data-access:10140
      - CATALOG_URL=http://catalog:10110

  pubsub:
    container_name: pubsub
    image: pubsub-emulator:latest
    build:
      context: docker/pubsub-emulator
      dockerfile: Dockerfile
    ports:
      - 8538:8538

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.16
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  db-admin:
    container_name: db-admin
    image: adminer
    ports:
      - 25430:8080

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    command: -N 500
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - 28081:8080
    volumes:
      - ./keycloak_ssb_realm.json:/tmp/ssb_realm.json
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/ssb_realm.json

  catalog:
    container_name: catalog
    build:
      context: ../dapla-catalog
      dockerfile: Dockerfile
    image: dapla-catalog-service:dev
    ports:
      - 20110:10110
      - 20118:10118
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/catalog
      AUTH_dash_SERVICE_HOST: user-access
      AUTH_dash_SERVICE_PORT: 10108
      PUBSUB_EMULATOR_HOST: pubsub
      PUBSUB_EMULATOR_PORT: 8538
      TRACING_HOST: jaeger
    depends_on:
      - postgres
      - jaeger
      - pubsub
      - user-access

  user-access:
    container_name: user-access
    build:
      context: ../dataset-access
      dockerfile: Dockerfile
    image: user-access:dev
    ports:
      - 20100:10100
      - 20108:10108
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/user_access
      TRACING_HOST: jaeger
    depends_on:
      - postgres
      - jaeger

  data-access:
    container_name: data-access
    build:
      context: ../data-access
      dockerfile: Dockerfile
    image: data-access:dev
    ports:
      - 20140:10140
      - 20148:10148
    volumes:
      - ./docker/data-access:/data-access-conf
      - ../dapla-spark-plugin/secret:/secret
    environment:
      TRACING_HOST: jaeger
      ROUTING_FILE: /data-access-conf/routing.json
      DATA_dash_ACCESS_PROVIDER: no.ssb.dapla.data.access.service.GoogleDataAccessService
      AUTH_dash_SERVICE_HOST: user-access
      AUTH_dash_SERVICE_PORT: 10108
      CATALOG_dash_SERVICE_HOST: catalog
      CATALOG_dash_SERVICE_PORT: 10118
    depends_on:
      - jaeger
      - user-access
      - catalog

  metadata-distributor:
    container_name: metadata-distributor
    build:
      context: ../metadata-distributor
      dockerfile: Dockerfile
    image: metadata-distributor:dev
    ports:
      - 20160:10160
      - 20168:10168
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
    environment:
      PUBSUB_EMULATOR_HOST: pubsub
      PUBSUB_EMULATOR_PORT: 8538
      TRACING_HOST: jaeger
      STORAGE_CLOUD_dash_STORAGE_ENABLED: "true"
      STORAGE_CLOUD_dash_STORAGE_CREDENTIALS_SERVICE_dash_ACCOUNT_PATH: /secret/gcs_sa_test.json
    depends_on:
      - jaeger
      - pubsub

volumes:
  pgdata:
