version: "3.7"

# These services depends on configuration from files:
#  - docker-compose.yml

services:

  concept-neo4j:
    container_name: concept-neo4j
    image: statisticsnorway/neo4j:4.1.3-lds
    ports:
      - 21074:7474
      - 21073:7473
      - 21087:7687
    volumes:
      - concept-neo4jdata:/data
    environment:
      - NEO4J_AUTH=neo4j/secret
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,lds.*

  concept-lds:
    container_name: concept-lds
    image: eu.gcr.io/prod-bip/ssb/lds-server:master-3df2c59e80318776f2223d0e77764ec1ae9fd5f7
    ports:
      - 29090:9090
    volumes:
      - ./docker/concept/graphqlschemas:/graphqlschemas
    environment:
      - JAVA_MODULE_SYSTEM_ENABLED=false
      - LDS_persistence.provider=neo4j
      - LDS_persistence.initialization.max-wait-seconds=60
      - LDS_neo4j.driver.url=bolt://concept-neo4j:7687
      - LDS_neo4j.driver.username=neo4j
      - LDS_neo4j.driver.password=secret
      - LDS_neo4j.cypher.show=false
      - LDS_saga.number-of-logs=5
      - LDS_sagalog.provider.initialization.max-wait-seconds=10
      - LDS_sagalog.provider.initialization.retry-interval-seconds=1
      - LDS_sagalog.provider=no.ssb.sagalog.postgres.PostgresSagaLogInitializer
      - LDS_sagalog.config.cluster.owner=concept-developer
      - LDS_sagalog.config.cluster.name=concept-localstack
      - LDS_sagalog.config.cluster.instance-id=01
      - LDS_sagalog.config.postgres.driver.host=postgres
      - LDS_sagalog.config.postgres.driver.port=5432
      - LDS_sagalog.config.postgres.driver.user=concept_sagalog
      - LDS_sagalog.config.postgres.driver.password=concept_sagalog
      - LDS_sagalog.config.postgres.driver.database=concept_sagalog
      - LDS_sagalog.config.connection-pool.max-size=10
      - LDS_txlog.split.sources=false
      - LDS_txlog.default-source=default
      - LDS_txlog.rawdata.topic-prefix=concept-txlog-
      - LDS_txlog.rawdata.provider.initialization.max-wait-seconds=10
      - LDS_txlog.rawdata.provider.initialization.retry-interval-seconds=1
      - LDS_txlog.rawdata.provider=postgres
      - LDS_txlog.config.postgres.driver.host=postgres
      - LDS_txlog.config.postgres.driver.port=5432
      - LDS_txlog.config.postgres.driver.user=concept_txlog
      - LDS_txlog.config.postgres.driver.password=concept_txlog
      - LDS_txlog.config.postgres.driver.database=concept_txlog
      - LDS_txlog.config.rawdata.postgres.consumer.prefetch-size=10
      - LDS_txlog.config.rawdata.postgres.consumer.prefetch-poll-interval-when-empty=1000
      - LDS_graphql.enabled=true
      - LDS_graphql.schema=/graphqlschemas/schema.graphql
      - LDS_graphql.search.enabled=false
    depends_on:
      - postgres
      - concept-neo4j

  dataset-doc-service:
    container_name: dataset-doc-service
    build:
      context: ../dataset-doc-service
      dockerfile: Dockerfile
    image: dataset-doc-service:dev
    ports:
      - 20190:10190
    environment:
      CONCEPT_dash_LDS_HOST: http://concept-lds
      CONCEPT_dash_LDS_PORT: 9090

volumes:
  concept-neo4jdata:
