version: "3.7"
services:
  spark-master:
    container_name: spark-master
    image: bde2020/spark-master:2.4.4-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
    ports:
      - 28000:8080
      - 28007:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  spark-worker-1:
    container_name: spark-worker-1
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
    depends_on:
      - spark-master
    ports:
      - 28011:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  spark-worker-2:
    container_name: spark-worker-2
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
    depends_on:
      - spark-master
    ports:
      - 28021:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  hadoop:
    container_name: hadoop
    image: sequenceiq/hadoop-docker:2.7.1
    ports:
      - 50070:50070
      - 50010:50010
      - 9000:9000

  zeppelin:
    container_name: zeppelin
    image: eu.gcr.io/prod-bip/dapla-zeppelin
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
      - ./notebook:/notebook:delegated
      - ./docker/zeppelin/shiro-localstack.ini:/zeppelin/conf/shiro.ini
    build:
      context: ../dapla-spark-plugin
      dockerfile: ${PWD}/../dapla-spark-plugin/docker/zeppelin/Dockerfile
    depends_on:
      - spark-master
      - keycloak
    ports:
      - 28010:8080
    env_file:
      - .env
    environment:
      - ZEPPELIN_SSB_USE_TOKENS=true
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_SERVER_JETTY_REQUEST_HEADER_SIZE=16384
      - SPARK_LOCAL_IP=zeppelin
      - SPARK_PRINT_LAUNCH_COMMAND=true
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_SUBMIT_DEPLOYMODE=client
      - DAPLA_SPARK_GCS_STORAGE=file:///data/datastore
      - DAPLA_SPARK_DATA_ACCESS_URL=http://data-access:10140
      - DAPLA_SPARK_METADATA_PUBLISHER_URL=http://metadata-distributor:10160
      - DAPLA_SPARK_METADATA_PUBLISHER_PROJECT_ID=dapla
      - DAPLA_SPARK_METADATA_PUBLISHER_TOPIC_NAME=file-events-1

  pubsub:
    container_name: pubsub
    image: pubsub-emulator:latest
    build:
      context: docker/pubsub-emulator
      dockerfile: Dockerfile
    ports:
      - 8538:8538

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.16
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  db-admin:
    container_name: db-admin
    image: adminer
    ports:
      - 25430:8080

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 25432:5432
    volumes:
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - 28081:8080
    volumes:
      - ./keycloak_ssb_realm.json:/tmp/ssb_realm.json
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/ssb_realm.json

  catalog:
    container_name: catalog
    build:
      context: ../dapla-catalog
      dockerfile: Dockerfile
    image: dapla-catalog-service:dev
    ports:
      - 20110:10110
      - 20118:10118
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/catalog
      AUTH_dash_SERVICE_HOST: user-access
      AUTH_dash_SERVICE_PORT: 10108
      PUBSUB_EMULATOR_HOST: pubsub
      PUBSUB_EMULATOR_PORT: 8538
      TRACING_HOST: jaeger
    depends_on:
      - postgres
      - jaeger
      - pubsub
      - user-access

  user-access:
    container_name: user-access
    build:
      context: ../dataset-access
      dockerfile: Dockerfile
    image: user-access:dev
    ports:
      - 20100:10100
      - 20108:10108
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/user_access
      TRACING_HOST: jaeger
    depends_on:
      - postgres
      - jaeger

  data-access:
    container_name: data-access
    build:
      context: ../data-access
      dockerfile: Dockerfile
    image: data-access:dev
    ports:
      - 20140:10140
      - 20148:10148
    volumes:
      - ../dapla-spark-plugin/secret:/secret
    environment:
      TRACING_HOST: jaeger
      DATA_ACCESS_SERVICE_ACCOUNT_KEY_FILE: /secret/gcs_sa_test.json
      DATA_ACCESS_SERVICE_DEFAULT_LOCATION: file:///data/datastore
      DATA_dash_ACCESS_PROVIDER: no.ssb.dapla.data.access.service.GoogleDataAccessService
      AUTH_dash_SERVICE_HOST: user-access
      AUTH_dash_SERVICE_PORT: 10108
      CATALOG_dash_SERVICE_HOST: catalog
      CATALOG_dash_SERVICE_PORT: 10118
    depends_on:
      - jaeger
      - user-access
      - catalog

  metadata-distributor:
    container_name: metadata-distributor
    build:
      context: ../metadata-distributor
      dockerfile: Dockerfile
    image: metadata-distributor:dev
    ports:
      - 20160:10160
      - 20168:10168
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
    environment:
      PUBSUB_EMULATOR_HOST: pubsub
      PUBSUB_EMULATOR_PORT: 8538
      TRACING_HOST: jaeger
      CLOUD_dash_STORAGE_ENABLED: "true"
      CLOUD_dash_STORAGE_CREDENTIALS_SERVICE_dash_ACCOUNT_PATH: /secret/gcs_sa_test.json
    depends_on:
      - jaeger
      - pubsub
