version: "3.7"

services:

  dapla-workbench:
    container_name: dapla-workbench
    image: eu.gcr.io/prod-bip/ssb/dapla/dapla-workbench:latest
    ports:
      - 28080:80
    environment:
      - NODE_ENV=development
      - REACT_APP_ENV=develop
      - REACT_APP_CONCEPT_LDS=http://localhost:29090
      - REACT_APP_CATALOG_SERVICE=http://localhost:20110
      - REACT_APP_EXPLORATION_LDS=http://localhost:29091
    depends_on:
      - catalog
      - concept-lds
      - exploration-lds

  dapla-metadata-explorer:
    container_name: metadata-explorer
    image: eu.gcr.io/prod-bip/ssb/dapla/dapla-metadata-explorer:latest
    ports:
      - 28083:80
    environment:
      - NODE_ENV=development
      - REACT_APP_CONCEPT_LDS=http://localhost:29090
      - REACT_APP_EXPLORATION_LDS=http://localhost:29091
    depends_on:
      - concept-lds
      - exploration-lds

  dapla-user-access-admin:
    container_name: dapla-user-access-admin
    image: eu.gcr.io/prod-bip/ssb/dapla/dapla-user-access-admin:latest
    ports:
      - 28082:80
    environment:
      - NODE_ENV=development
      - REACT_APP_API_AUTH=http://localhost:20100
      - REACT_APP_API_CATALOG=http://localhost:20110
    depends_on:
      - catalog
      - user-access