version: "3.7"
services:
  spark-master:
    container_name: spark-master
    image: bde2020/spark-master:2.4.5-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
    ports:
      - 28000:8080
      - 28007:7077
    expose:
      - 7337
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  spark-worker-1:
    container_name: spark-worker-1
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
      - ./docker/spark-worker/worker.sh:/worker.sh
    depends_on:
      - spark-master
    ports:
      - 28011:8081
    expose:
      - 7337
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  spark-worker-2:
    container_name: spark-worker-2
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
      - ./docker/spark-worker/worker.sh:/worker.sh
    depends_on:
      - spark-master
    ports:
      - 28021:8081
    expose:
      - 7337
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DAPLA_SPARK_SERVICE_ACCOUNT_KEY_FILE=/secret/gcs_sa_test.json

  jupyter:
    container_name: jupyter
    image: eu.gcr.io/prod-bip/dapla-jupyter
    volumes:
      - ./data:/data:delegated
      - ./docker/jupyter/jupyterhub_config.py:/jupyter/jupyterhub_config.py
      - ./docker/jupyter/spark-localstack.conf:/usr/lib/spark/conf/spark-defaults.conf
    build:
      context: ../dapla-spark-plugin
      dockerfile: ${PWD}/../dapla-spark-plugin/docker/jupyter/Dockerfile
    depends_on:
      - spark-master
      - keycloak
    ports:
      - 28012:8000
    environment:
      - JUPYTERHUB_HANDLER_CUSTOM_AUTH_URL=https://127.0.0.1:8081/hub/custom-api/user
      - SPARK_USER_TOKEN_EXPIRY_BUFFER_SECS=10
      - OAUTH2_AUTH_URL=http://localhost:28081/auth/realms/ssb/protocol/openid-connect/auth
      - OAUTH2_TOKEN_URL=http://keycloak:8080/auth/realms/ssb/protocol/openid-connect/token
      - OAUTH2_USERDATA_URL=http://keycloak:8080/auth/realms/ssb/protocol/openid-connect/userinfo
      - OAUTH2_CALLBACK_URL=http://localhost:28012/hub/oauth_callback
      - OAUTH_CLIENT_ID=jupyter
      - OAUTH_CLIENT_SECRET=f506d183-77ec-446c-a51b-af4ec7daef81
      - METADATA_PUBLISHER_URL=http://metadata-distributor:10160
      - DATA_ACCESS_URL=http://data-access:10140
      - CATALOG_URL=http://catalog:10110

  zeppelin:
    container_name: zeppelin
    image: eu.gcr.io/prod-bip/dapla-zeppelin
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
      - ./notebook:/notebook:delegated
      - ./docker/zeppelin/shiro-localstack.ini:/zeppelin/conf/shiro.ini
    build:
      context: ../dapla-spark-plugin
      dockerfile: ${PWD}/../dapla-spark-plugin/docker/zeppelin/Dockerfile
    depends_on:
      - spark-master
      - keycloak
    ports:
      - 28010:8080
    env_file:
      - .env
    environment:
      - ZEPPELIN_SSB_USE_TOKENS=true
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_SERVER_JETTY_REQUEST_HEADER_SIZE=16384
      - SPARK_LOCAL_IP=zeppelin
      - SPARK_PRINT_LAUNCH_COMMAND=true
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_SUBMIT_DEPLOYMODE=client
      - SPARK_DYNAMICALLOCATION_ENABLED=true
      - SPARK_SHUFFLE_SERVICE_ENABLED=true
      - DAPLA_SPARK_DATA_ACCESS_URL=http://data-access:10140
      - DAPLA_SPARK_CATALOG_URL=http://catalog:10110
      - DAPLA_SPARK_METADATA_PUBLISHER_URL=http://metadata-distributor:10160
      - DAPLA_SPARK_METADATA_PUBLISHER_PROJECT_ID=dapla
      - DAPLA_SPARK_METADATA_PUBLISHER_TOPIC_NAME=file-events-1
      - DAPLA_SPARK_OAUTH_TOKEN_URL=http://keycloak:8080/auth/realms/ssb/protocol/openid-connect/token
      - DAPLA_SPARK_OAUTH_TRACING_URL=http://jaeger:14268/api/traces
      - DAPLA_SPARK_OAUTH_CLIENT_ID=zeppelin
      - DAPLA_SPARK_OAUTH_CLIENT_SECRET=ed48ee94-fe9d-4096-b069-9626a52877f2

  pubsub:
    container_name: pubsub
    image: pubsub-emulator:latest
    build:
      context: docker/pubsub-emulator
      dockerfile: Dockerfile
    ports:
      - 8538:8538

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.16
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  db-admin:
    container_name: db-admin
    image: adminer
    ports:
      - 25430:8080

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    command: -N 500
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  solr:
    container_name: solr
    image: solr:8
    ports:
      - 28983:8983
    volumes:
      - solrdata:/var/solr
    entrypoint:
      - bash
      - "-c"
      - "precreate-core gsim; precreate-core concept; exec solr -f"

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - 28081:8080
    volumes:
      - ./keycloak_ssb_realm.json:/tmp/ssb_realm.json
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/ssb_realm.json

  catalog:
    container_name: catalog
    build:
      context: ../dapla-catalog
      dockerfile: Dockerfile
    image: dapla-catalog-service:dev
    ports:
      - 20110:10110
      - 20118:10118
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/catalog
      AUTH_dash_SERVICE_HOST: user-access
      AUTH_dash_SERVICE_PORT: 10108
      PUBSUB_EMULATOR_HOST: pubsub
      PUBSUB_EMULATOR_PORT: 8538
      TRACING_HOST: jaeger
    depends_on:
      - postgres
      - jaeger
      - pubsub
      - user-access

  user-access:
    container_name: user-access
    build:
      context: ../dataset-access
      dockerfile: Dockerfile
    image: user-access:dev
    ports:
      - 20100:10100
      - 20108:10108
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/user_access
      TRACING_HOST: jaeger
    depends_on:
      - postgres
      - jaeger

  data-access:
    container_name: data-access
    build:
      context: ../data-access
      dockerfile: Dockerfile
    image: data-access:dev
    ports:
      - 20140:10140
      - 20148:10148
    volumes:
      - ./docker/data-access:/data-access-conf
      - ../dapla-spark-plugin/secret:/secret
    environment:
      TRACING_HOST: jaeger
      ROUTING_FILE: /data-access-conf/routing.json
      DATA_dash_ACCESS_PROVIDER: no.ssb.dapla.data.access.service.GoogleDataAccessService
      AUTH_dash_SERVICE_HOST: user-access
      AUTH_dash_SERVICE_PORT: 10108
      CATALOG_dash_SERVICE_HOST: catalog
      CATALOG_dash_SERVICE_PORT: 10118
    depends_on:
      - jaeger
      - user-access
      - catalog

  metadata-distributor:
    container_name: metadata-distributor
    build:
      context: ../metadata-distributor
      dockerfile: Dockerfile
    image: metadata-distributor:dev
    ports:
      - 20160:10160
      - 20168:10168
    volumes:
      - ./data:/data:delegated
      - ../dapla-spark-plugin/secret:/secret
    environment:
      PUBSUB_EMULATOR_HOST: pubsub
      PUBSUB_EMULATOR_PORT: 8538
      TRACING_HOST: jaeger
      STORAGE_CLOUD_dash_STORAGE_ENABLED: "true"
      STORAGE_CLOUD_dash_STORAGE_CREDENTIALS_SERVICE_dash_ACCOUNT_PATH: /secret/gcs_sa_test.json
    depends_on:
      - jaeger
      - pubsub

  concept-lds:
    container_name: concept-lds
    image: statisticsnorway/lds-server:1.0.2
    ports:
      - 29090:9090
    volumes:
      - ./docker/concept/graphqlschemas:/graphqlschemas
    environment:
      - JAVA_MODULE_SYSTEM_ENABLED=true
      - LDS_persistence.provider=postgres
      - LDS_persistence.initialization.max-wait-seconds=10
      - LDS_postgres.driver.host=postgres
      - LDS_postgres.driver.port=5432
      - LDS_postgres.driver.user=concept
      - LDS_postgres.driver.password=concept
      - LDS_postgres.driver.database=concept
      - LDS_saga.number-of-logs=5
      - LDS_sagalog.provider=no.ssb.sagalog.postgres.PostgresSagaLogInitializer
      - LDS_sagalog.config.cluster.owner=concept-developer
      - LDS_sagalog.config.cluster.name=concept-localstack
      - LDS_sagalog.config.cluster.instance-id=01
      - LDS_sagalog.config.postgres.driver.host=postgres
      - LDS_sagalog.config.postgres.driver.port=5432
      - LDS_sagalog.config.postgres.driver.user=concept_sagalog
      - LDS_sagalog.config.postgres.driver.password=concept_sagalog
      - LDS_sagalog.config.postgres.driver.database=concept_sagalog
      - LDS_sagalog.config.connection-pool.max-size=10
      - LDS_txlog.split.sources=false
      - LDS_txlog.default-source=default
      - LDS_txlog.rawdata.topic-prefix=concept-txlog-
      - LDS_txlog.rawdata.provider=postgres
      - LDS_txlog.config.postgres.driver.host=postgres
      - LDS_txlog.config.postgres.driver.port=5432
      - LDS_txlog.config.postgres.driver.user=concept_txlog
      - LDS_txlog.config.postgres.driver.password=concept_txlog
      - LDS_txlog.config.postgres.driver.database=concept_txlog
      - LDS_txlog.config.rawdata.postgres.consumer.prefetch-size=10
      - LDS_txlog.config.rawdata.postgres.consumer.prefetch-poll-interval-when-empty=1000
      - LDS_graphql.enabled=true
      - LDS_graphql.schema=/graphqlschemas/schema.graphql
      - LDS_graphql.search.enabled=true
      - LDS_search.index.provider=solr
      - LDS_search.index.url=http://solr:8983/solr/concept
    depends_on:
      - postgres
      - solr

  gsim-lds:
    container_name: gsim-lds
    image: statisticsnorway/lds-server:1.0.2
    ports:
      - 29091:9091
    volumes:
      - ./docker/gsim/graphqlschemas:/graphqlschemas
    environment:
      - JAVA_MODULE_SYSTEM_ENABLED=true
      - LDS_http.port=9091
      - LDS_persistence.provider=postgres
      - LDS_persistence.initialization.max-wait-seconds=10
      - LDS_postgres.driver.host=postgres
      - LDS_postgres.driver.port=5432
      - LDS_postgres.driver.user=gsim
      - LDS_postgres.driver.password=gsim
      - LDS_postgres.driver.database=gsim
      - LDS_saga.number-of-logs=5
      - LDS_sagalog.provider=no.ssb.sagalog.postgres.PostgresSagaLogInitializer
      - LDS_sagalog.config.cluster.owner=gsim-developer
      - LDS_sagalog.config.cluster.name=gsim-localstack
      - LDS_sagalog.config.cluster.instance-id=01
      - LDS_sagalog.config.postgres.driver.host=postgres
      - LDS_sagalog.config.postgres.driver.port=5432
      - LDS_sagalog.config.postgres.driver.user=gsim_sagalog
      - LDS_sagalog.config.postgres.driver.password=gsim_sagalog
      - LDS_sagalog.config.postgres.driver.database=gsim_sagalog
      - LDS_sagalog.config.connection-pool.max-size=10
      - LDS_txlog.split.sources=true
      - LDS_txlog.default-source=default
      - LDS_txlog.rawdata.topic-prefix=gsim-txlog-
      - LDS_txlog.rawdata.provider=postgres
      - LDS_txlog.config.postgres.driver.host=postgres
      - LDS_txlog.config.postgres.driver.port=5432
      - LDS_txlog.config.postgres.driver.user=gsim_txlog
      - LDS_txlog.config.postgres.driver.password=gsim_txlog
      - LDS_txlog.config.postgres.driver.database=gsim_txlog
      - LDS_txlog.config.rawdata.postgres.consumer.prefetch-size=10
      - LDS_txlog.config.rawdata.postgres.consumer.prefetch-poll-interval-when-empty=1000
      - LDS_graphql.enabled=true
      - LDS_graphql.schema=/graphqlschemas/schema.graphql
      - LDS_graphql.search.enabled=true
      - LDS_search.index.provider=solr
      - LDS_search.index.url=http://solr:8983/solr/gsim
    depends_on:
      - postgres
      - solr

  lds-client:
    container_name: lds-client
    image: statisticsnorway/linked-data-store-client:latest
    ports:
      - 28080:80

  variable-search:
    container_name: variable-search
    image: statisticsnorway/variable-search:latest
    ports:
      - 28082:80

  gsim-metadata-ingest:
    container_name: gsim-metadata-ingest
    build:
      context: ../dapla-gsim-metadata-ingest
      dockerfile: Dockerfile
    image: gsim-metadata-ingest:dev
    ports:
      - 20230:10230
    environment:
      - JAVA_MODULE_SYSTEM_ENABLED=false
      - PUBSUB_ENABLED=true
      - PUBSUB_ADMIN=true
      - PUBSUB_USE_dash_EMULATOR=true
      - PUBSUB_EMULATOR_HOST=pubsub
      - PUBSUB_EMULATOR_PORT=8538
      - PUBSUB_UPSTREAM_PROJECTID=dapla
      - PUBSUB_UPSTREAM_TOPIC=gsim-metadata-1
      - PUBSUB_UPSTREAM_SUBSCRIPTION=gsim-metadata-dev
    depends_on:
      - pubsub
      - gsim-lds

  gsim-concept-ingest:
    container_name: gsim-concept-ingest
    build:
      context: ../dapla-gsim-concept-ingest
      dockerfile: Dockerfile
    image: gsim-concept-ingest:dev
    ports:
      - 20240:10240
    environment:
      - JAVA_MODULE_SYSTEM_ENABLED=false
      - PIPE_SOURCE_TOPIC=concept-txlog-default
      - PIPE_SOURCE_PROVIDER_NAME=postgres
      - PIPE_SOURCE_PROVIDER_CONFIG_POSTGRES_DRIVER_HOST=postgres
      - PIPE_SOURCE_PROVIDER_CONFIG_POSTGRES_DRIVER_PORT=5432
      - PIPE_SOURCE_PROVIDER_CONFIG_POSTGRES_DRIVER_USER=concept_txlog
      - PIPE_SOURCE_PROVIDER_CONFIG_POSTGRES_DRIVER_PASSWORD=concept_txlog
      - PIPE_SOURCE_PROVIDER_CONFIG_POSTGRES_DRIVER_DATABASE=concept_txlog
      - PIPE_SOURCE_PROVIDER_CONFIG_RAWDATA_POSTGRES_CONSUMER_PREFETCH_dash_SIZE=10
      - PIPE_SOURCE_PROVIDER_CONFIG_RAWDATA_POSTGRES_CONSUMER_PREFETCH_dash_POLL_dash_INTERVAL_dash_WHEN_dash_EMPTY=1000
      - PIPE_TARGET_SCHEME=http
      - PIPE_TARGET_HOST=gsim-lds
      - PIPE_TARGET_PORT=9091
      - PIPE_TARGET_NAMESPACE=ns
      - PIPE_TARGET_SOURCE=concept
    depends_on:
      - concept-lds
      - gsim-lds

volumes:
  pgdata:
  solrdata:
