version: "3.7"

# These services depends on configuration from files:
#  - docker-compose.yml

services:

  solr:
    container_name: solr
    image: solr:8
    ports:
      - 28983:8983
    volumes:
      - solrdata:/var/solr
    entrypoint:
      - bash
      - "-c"
      - "precreate-core exploration; precreate-core concept; exec solr -f"

  concept-lds:
    container_name: concept-lds
    image: statisticsnorway/lds-server:1.0.8
    ports:
      - 29090:9090
    volumes:
      - ./docker/concept/graphqlschemas:/graphqlschemas
    environment:
      - JAVA_MODULE_SYSTEM_ENABLED=false
      - LDS_persistence.provider=postgres
      - LDS_persistence.initialization.max-wait-seconds=10
      - LDS_postgres.driver.host=postgres
      - LDS_postgres.driver.port=5432
      - LDS_postgres.driver.user=concept
      - LDS_postgres.driver.password=concept
      - LDS_postgres.driver.database=concept
      - LDS_saga.number-of-logs=5
      - LDS_sagalog.provider.initialization.max-wait-seconds=10
      - LDS_sagalog.provider.initialization.retry-interval-seconds=1
      - LDS_sagalog.provider=no.ssb.sagalog.postgres.PostgresSagaLogInitializer
      - LDS_sagalog.config.cluster.owner=concept-developer
      - LDS_sagalog.config.cluster.name=concept-localstack
      - LDS_sagalog.config.cluster.instance-id=01
      - LDS_sagalog.config.postgres.driver.host=postgres
      - LDS_sagalog.config.postgres.driver.port=5432
      - LDS_sagalog.config.postgres.driver.user=concept_sagalog
      - LDS_sagalog.config.postgres.driver.password=concept_sagalog
      - LDS_sagalog.config.postgres.driver.database=concept_sagalog
      - LDS_sagalog.config.connection-pool.max-size=10
      - LDS_txlog.split.sources=false
      - LDS_txlog.default-source=default
      - LDS_txlog.rawdata.topic-prefix=concept-txlog-
      - LDS_txlog.rawdata.provider.initialization.max-wait-seconds=10
      - LDS_txlog.rawdata.provider.initialization.retry-interval-seconds=1
      - LDS_txlog.rawdata.provider=postgres
      - LDS_txlog.config.postgres.driver.host=postgres
      - LDS_txlog.config.postgres.driver.port=5432
      - LDS_txlog.config.postgres.driver.user=concept_txlog
      - LDS_txlog.config.postgres.driver.password=concept_txlog
      - LDS_txlog.config.postgres.driver.database=concept_txlog
      - LDS_txlog.config.rawdata.postgres.consumer.prefetch-size=10
      - LDS_txlog.config.rawdata.postgres.consumer.prefetch-poll-interval-when-empty=1000
      - LDS_graphql.enabled=true
      - LDS_graphql.schema=/graphqlschemas/schema.graphql
      - LDS_graphql.search.enabled=true
      - LDS_search.index.provider=solr
      - LDS_search.index.url=http://solr:8983/solr/concept
    depends_on:
      - postgres
      - solr

  lds-client:
    container_name: lds-client
    image: statisticsnorway/linked-data-store-client:latest
    ports:
      - 28080:80

  dataset-doc-service:
    container_name: dataset-doc-service
    build:
      context: ../dataset-doc-service
      dockerfile: Dockerfile
    image: dataset-doc-service:dev
    ports:
      - 20190:10190

volumes:
  solrdata:
