version: "3.7"
services:
  spark-master:
    container_name: spark-master
    image: bde2020/spark-master:2.4.4-hadoop2.7
    volumes:
      - ./data:/data
    ports:
      - 18000:8080
      - 18007:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    container_name: spark-worker-1
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    volumes:
      - ./data:/data
    depends_on:
      - spark-master
    ports:
      - 18001:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  spark-worker-2:
    container_name: spark-worker-2
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    volumes:
      - ./data:/data
    depends_on:
      - spark-master
    ports:
      - 18002:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  hadoop:
    container_name: hadoop
    image: sequenceiq/hadoop-docker:2.7.1
    ports:
      - 50070:50070
      - 50010:50010
      - 9000:9000

  zeppelin:
    container_name: zeppelin-notebook
    image: lds-zeppelin:latest
    volumes:
      - ./data:/data
      - ./notebook:/notebook:delegated
    build:
      context: ../
      dockerfile: ${PWD}/docker/zeppelin/Dockerfile
    depends_on:
    - spark-master
    ports:
      - 18010:8080
    env_file:
      - .env
    environment:
      - SPARK_MASTER_HOST=spark://spark-master
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - SPARK_LOCAL_IP=zeppelin
      - SPARK_PRINT_LAUNCH_COMMAND=true
      - ZEPPELIN_ADDR=0.0.0.0

  db-admin:
    container_name: db-admin
    image: adminer
    ports:
      - 18020:8080

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    ports:
      - 15432:5432
    volumes:
      - ../dataset-access/init-db.sql:/docker-entrypoint-initdb.d/init.sql  

  bigtable:
    container_name: bigtable
    image: statisticsnorway/bigtable-emulator
    ports:
      - 19035:9035

  dapla-noterepo-service:
    container_name: dapla-noterepo-service
    build: 
        context: ../dapla-noterepo
        dockerfile: service/Dockerfile
    image: dapla-noterepo-service:dev
    ports:
      - 18050:8080
      - 18052:1408

  dapla-spark-service:
    container_name: dapla-spark-service
    build: 
        context: ../dapla-spark
        dockerfile: service/Dockerfile
    image: dapla-spark-service:dev
    ports:
      - 18060:8060
      - 18062:1408

  dapla-catalog-service:
    container_name: dapla-catalog-service
    build: 
        context: ../dapla-catalog
        dockerfile: Dockerfile  
    image: dapla-catalog-service:dev
    ports:
      - 18070:8070
      - 18072:1408
    environment:
      BIGTABLE_HOST: bigtable
      AUTH_dash_SERVICE_HOST: dapla-auth-dataset-service
      AUTH_dash_SERVICE_PORT: 7070
    depends_on:
      - bigtable

  dapla-auth-dataset-service:
    container_name: dapla-auth-dataset-service
    build: 
        context: ../dataset-access
        dockerfile: Dockerfile
    image: dapla-auth-dataset-service:dev
    ports:
      - 18080:8080
      - 18082:7070
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: 172.17.0.1
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 15432
      FLYWAY_URL: jdbc:postgresql://172.17.0.1:15432/rdc
    depends_on:
      - postgres

    
  
